# .github/labeler.yml

documentation:
  - changed-files:
    - any-glob-to-any-file: "README.md"

code:
  - changed-files:
    - any-glob-to-any-file: "src/**"

tests:
  - changed-files:
    - any-glob-to-any-file: "tests/**"

markdown:
  - changed-files:
    - any-glob-to-any-file: "*.md"
