# .github/labeler.yml

- label: "documentation"
  paths:
    - "README.md"

- label: "code"
  paths:
    - "src/**"

- label: "tests"
  paths:
    - "tests/**"

- label: "markdown"
  paths:
    - "*.md"
