name: Close Preview
on:
  issue_comment:
    types: [created]
jobs:
  close-preview:
    if: github.event.comment.body == '!close_preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if this PR has the preview
        id: check_preview
        run: |
          if [ -f .preview_status ] && [ "$(cat .preview_status)" == "${{ github.event.issue.number }}" ]; then
            echo "has_preview=true" >> $GITHUB_OUTPUT
          else
            echo "has_preview=false" >> $GITHUB_OUTPUT
          fi

      - name: Close preview
        if: steps.check_preview.outputs.has_preview == 'true'
        run: |
          rm .preview_status
          git config user.name "dd-anish"
          git config user.email "anish@deardigital.com"
          git add .preview_status
          git commit -m "Close preview for PR #${{ github.event.issue.number }}"
          git push origin development-preview

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const message = steps.check_preview.outputs.has_preview == 'true'
              ? 'Preview has been closed successfully.'
              : 'This PR does not currently have an active preview.';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
