name: Preview Deployment

on:
  issue_comment:
    types: [created]

jobs:
  preview-deployment:
    if: github.event.comment.body == '!preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "dd-anish"
          git config user.email "anish@deardigital.com"

      - name: Check out the development-preview branch
        run: git checkout development-preview || git checkout -b development-preview

      - name: Remove all files from development-preview
        run: |
          git rm -rf .
          git clean -fd
          git commit -m "Clear development-preview branch"

      - name: Check out the PR branch
        run: git fetch origin +refs/pull/${{ github.event.issue.number }}/head:pr-branch

      - name: Merge PR branch into development-preview
        run: |
          git checkout development-preview
          git merge pr-branch --allow-unrelated-histories --no-ff -m "Merging PR #${{ github.event.issue.number }} into development-preview"
          git push origin development-preview --force
