name: Preview Deployment

on:
  issue_comment:
    types: [created]

jobs:
  preview-deployment:
    if: github.event.comment.body == '!preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "dd-anish"
          git config user.email "anish@deardigital.com"

      - name: Check out the development-preview branch
        run: git checkout development-preview || git checkout -b development-preview

      - name: Fetch PR branch
        run: git fetch origin +refs/pull/${{ github.event.issue.number }}/head:pr-branch

      - name: Reset development-preview to PR branch
        run: |
          git checkout development-preview
          git reset --hard pr-branch
          git push origin development-preview --force
