name: Preview Deployment
on:
  issue_comment:
    types: [created]
jobs:
  preview-deployment:
    if: github.event.comment.body == '!preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "dd-anish"
          git config user.email "anish@deardigital.com"

      - name: Check current preview status
        id: check_preview
        run: |
          if [ -f .preview_status ]; then
            CURRENT_PR=$(cat .preview_status)
            if [ "$CURRENT_PR" != "${{ github.event.issue.number }}" ]; then
              echo "status=occupied" >> $GITHUB_OUTPUT
              echo "current_pr=$CURRENT_PR" >> $GITHUB_OUTPUT
            else
              echo "status=same_pr" >> $GITHUB_OUTPUT
            fi
          else
            echo "status=available" >> $GITHUB_OUTPUT
          fi

      - name: Handle occupied preview
        if: steps.check_preview.outputs.status == 'occupied'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const comment = `The preview theme is currently being used by PR #${{ steps.check_preview.outputs.current_pr }}. Please close that preview first by commenting '!close_preview' on that PR before requesting a new preview.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });

      - name: Deploy preview
        if: steps.check_preview.outputs.status != 'occupied'
        run: |
          # Your deployment steps here
          echo "${{ github.event.issue.number }}" > .preview_status
          git add .preview_status
          git commit -m "Update preview status for PR #${{ github.event.issue.number }}"
          git push origin development-preview

      - name: Generate preview link
        if: steps.check_preview.outputs.status != 'occupied'
        id: preview_link
        run: |
          PREVIEW_URL="https://${{ secrets.SHOP_STORE }}/?preview_theme_id=129969324118"
          echo "PREVIEW_LINK=${PREVIEW_URL}" >> $GITHUB_OUTPUT

      - name: Post comment with preview link
        if: steps.check_preview.outputs.status != 'occupied'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const comment = `You can see the [Preview Theme](${{ steps.preview_link.outputs.PREVIEW_LINK }})\n\nTo close this preview when you're done, comment '!close_preview' on this PR.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
