name: Preview Deployment

on:
  issue_comment:
    types: [created]

env:
  USER_NAME: 'dd-anish'
  USER_EMAIL: 'anish@deardigital.com'
  SHOP_STORE: 'anish-test-store.myshopify.com'
  THEME_ID: '129969324118'

jobs:
  preview-deployment:
    if: github.event.comment.body == '!preview' || github.event.comment.body == '!close_preview'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ env.USER_NAME }}"
          git config user.email "${{ env.USER_EMAIL }}"

      - name: Check out the development-preview branch
        run: git checkout development-preview || git checkout -b development-preview

      - name: Check current preview status
        id: check_preview
        run: |
          if [ -f .preview_status ]; then
            CURRENT_PR=$(cat .preview_status)
            if [ "$CURRENT_PR" != "${{ github.event.issue.number }}" ]; then
              echo "status=occupied" >> $GITHUB_OUTPUT
              echo "current_pr=$CURRENT_PR" >> $GITHUB_OUTPUT
            else
              echo "status=same_pr" >> $GITHUB_OUTPUT
            fi
          else
            echo "status=available" >> $GITHUB_OUTPUT
          fi

      - name: Handle occupied preview
        if: github.event.comment.body == '!preview' && steps.check_preview.outputs.status == 'occupied'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const comment = `The preview theme is currently being used by PR #${{ steps.check_preview.outputs.current_pr }}.\n\nPlease close that preview first by commenting '!close_preview' on that PR before requesting a new preview.`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: comment
            });

      - name: Close preview
        if: github.event.comment.body == '!close_preview'
        id: close_preview
        run: |
          if [ -f .preview_status ] && [ "$(cat .preview_status)" == "${{ github.event.issue.number }}" ]; then
            rm .preview_status
            git add .preview_status
            git commit -m "Close preview for PR #${{ github.event.issue.number }}"
            git push origin development-preview
            echo "closed=true" >> $GITHUB_OUTPUT
          else
            echo "closed=false" >> $GITHUB_OUTPUT
          fi

      - name: Fetch and reset to PR branch
        if: github.event.comment.body == '!preview' && steps.check_preview.outputs.status != 'occupied'
        run: |
          git fetch origin +refs/pull/${{ github.event.issue.number }}/head:pr-branch
          git checkout development-preview
          git reset --hard pr-branch
          echo "${{ github.event.issue.number }}" > .preview_status
          git add .preview_status
          git commit -m "Update preview status for PR #${{ github.event.issue.number }}"
          git push origin development-preview --force

      - name: Generate preview link
        if: github.event.comment.body == '!preview' && steps.check_preview.outputs.status != 'occupied'
        id: preview_link
        run: |
          PREVIEW_URL="https://${{ env.SHOP_STORE }}/?preview_theme_id=${{ env.THEME_ID }}"
          echo "PREVIEW_LINK=${PREVIEW_URL}" >> $GITHUB_OUTPUT

      - name: Post comment with preview link
        if: github.event.comment.body == '!preview' && steps.check_preview.outputs.status != 'occupied'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const comment = `You can see the [Preview Theme](${{ steps.preview_link.outputs.PREVIEW_LINK }})\n\nTo close this preview when you're done, comment '!close_preview' on this PR.`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: comment
            });

      - name: Comment on close preview
        if: github.event.comment.body == '!close_preview'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const message = '${{ steps.close_preview.outputs.closed }}' === 'true'
              ? 'Preview has been closed successfully.'
              : 'This PR does not currently have an active preview.';
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: message
            });
