name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: 
      - opened       # When a pull request is opened
      - edited       # When a pull request is edited
      - reopened     # When a pull request is reopened
      - synchronize   # When commits are pushed to the pull request

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false  # Change to true if you want to lint the entire codebase
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
